name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      with:
          # FTP server name (you may need to specify a port)
          ftp_server: ta18raamat.itmajakas.ee
          # FTP account username
          ftp_username: vadim.ta18raamat.itmajakas.ee
          # FTP account password
          ftp_password: $FTP_PAROOL
          # The port used to connect to server
          port: 21
          # The remote folder to copy to, deafults to root FTP folder (I recommend you configure this on your server side instead of here)
          remote_dir: /kapityhjendaja